# Generated by Django 3.0.4 on 2020-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='email',
            field=models.EmailField(default='not available', max_length=254),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='xyz', max_length=10),
        ),
    ]
